Java Collections Stream API Homework
genroelgvozo/hh-school-2022-java-collections-stream pull request #14
Opened 2022-12-24 17:21 UTC by alextoritsin

1. В Task1-7 прописаны рабочие методы с прохождением всех тестов;
2. Изменения в Task 8:

- реализация пропуска первого элемента в методе `getNames` выполнена с помощью метода `skip()`.
- из возвращаемого значения метода `getDifferentNames` убран `distinct()`, так как Set уже возвращает уникальные значения;
- метод `convertPersonToString` переписан с использованием форматированной строки, теперь он возвращает строку без лишних пробелов, если пользователь передал пробел вместо имени;
- в методе `getPersonNames` изменен размер HashMap с 1 (единицы) до 1,5 размеров передаваемой коллекции;
- проверка на совпадающие имена в методе `hasSamePersons` теперь проходит с помощью пересечения множеств, созданных из переданных коллекций;
- подсчёт всех элементов в методе `countEven` теперь проходит с использованием метода стрима `count()` без использования дополнительного счетчика.

2022-12-25 18:40 UTC, genroelgvozo requested changes

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    List<Person> listOfPersons = personIds
1. сбор в мапу лучше выглядит через стримы
2. переменная не нужна, если сразу return - пиши выражение сразу в нем

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task2.java
> +      .sorted(comparator)
зачем компаратор выносить в переменную?

ну и про return видимо ко всем задачам относится

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +      .sorted(comparator)
код может упасть

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task4.java
> +      .map(person -> personConverter.convert(person))
personConverter::convert можно

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task7.java
> +        .stream().map(vacancy -> vacancy.getTitle()))
лучше выносить лишние методы из под flatMap для читабельности, чтобы не искать где там скобки какие закрываются

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return getNames(persons).stream().collect(Collectors.toSet());
а дальше идея не подсказала что это не нужно все?)
ну и прямо пример с лекции с последних слайдов, ну как так

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return String.join(" ", result.trim().split("\\s+"));
прекрасно, сначала джойним, потом еще раз сплитим и еще раз джойним)
и все чтобы избавиться от пробелов

а по факту, в финале ты что написал - берем массив строк нужных, избавляемся от null или пустых (это чуть выше было) и джойним все - хмм, есть же Collectors.joining

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    int initialCapacity = persons.size() + persons.size() / 2;
точно такой должен быть в бизнес логике, чето не хочу в такое вникать

да, без начального capacity будет пару раз расширение, но это точно лучше чем с 1
ну и давай на стрим перепишем, тут какой-то ифчик еще зачем-то

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return true;
можно в сет превратить только одну коллекцию (чуток места сэкономить) и чуть менее косвенная проверка (а то в проверку размера надо еще вникнуть), прям код так и должен говорить - если хотя бы одна персона отсюда есть тута

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return true;
и все так же за O(n+m)

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return String.join(" ", result.trim().split("\\s+"));
тут просто важно понимать - через стримы ты перепишешь, и будет 3 строки почти что человеческого текста "что надо сделать" , а ты тут пишешь "как надо сделать", еще и регэксп используешь (сгинь), в таком коде проще ошибиться

2022-12-25 18:40 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +      .count();
а чем плохо было изначально то?

2022-12-26 21:20 UTC, alextoritsin commented on src/main/java/tasks/Task2.java
> +      .sorted(comparator)
переделал все return, убрал лишние переменные

2022-12-26 21:20 UTC, alextoritsin commented on src/main/java/tasks/Task3.java
> +      .sorted(comparator)
добавил проверку на null

2022-12-26 21:21 UTC, alextoritsin commented on src/main/java/tasks/Task4.java
> +      .map(person -> personConverter.convert(person))
добавил метод референс, где это уместно

2022-12-26 21:22 UTC, alextoritsin commented on src/main/java/tasks/Task7.java
> +        .stream().map(vacancy -> vacancy.getTitle()))
переделал этот стрим, вроде лучше стало читаться)

2022-12-26 21:23 UTC, alextoritsin commented on src/main/java/tasks/Task8.java
> +    return getNames(persons).stream().collect(Collectors.toSet());
подсказала, все оказалось довольно просто)

2022-12-26 21:23 UTC, alextoritsin commented on src/main/java/tasks/Task8.java
> +    return String.join(" ", result.trim().split("\\s+"));
действительно, теперь все выглядит по человечески)

2022-12-26 21:25 UTC, alextoritsin commented on src/main/java/tasks/Task8.java
> +    int initialCapacity = persons.size() + persons.size() / 2;
переписал, все намного понятнее стало

2022-12-26 21:26 UTC, alextoritsin commented on src/main/java/tasks/Task8.java
> +    return true;
сделал, вроде лаконичнее смотрится

2022-12-26 21:27 UTC, alextoritsin commented on src/main/java/tasks/Task8.java
> +      .count();
все таки оставил на стримах, переменная count больше не нужна и лучше читаемость, как мне кажется)

2022-12-30 07:25 UTC, genroelgvozo approved these changes

2022-12-30 07:25 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +      .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
код упадет, а мой нет)

2023-08-04 15:46 UTC, closed without merging